### PR TITLE
Added get it on F-Droid button

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Perhaps remove fdfilter=tinfoil& from the url if you want to.

**Comment by relan** [comment]
This is an outdated version of the badge. Please see [this instruction](https://gitlab.com/fdroid/artwork/blob/master/badge/README.md).

**Comment by adrian-bl** [comment]
Added a readme with the recommended markup

**Comment by relan** [comment]
> Added a readme

Could you please also add LICENSE file?

**Comment by adrian-bl** [comment]
sure: done in commit eeed4b92de658744db17529f070750213341dca1

**Comment by relan** [comment]
Thanks! I've noticed that F-Droid says vanilla-headphone-detector is GPLv3+, but there was no license info in the repo. Now it's definitely free software. :)

**Comment by adrian-bl** [comment]
Well, there was always the GPLv3 boilerplate in the source files, but having a LICENSE file is indeed much nicer :)

**Pull request closed without merging**
